apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: gg7cev9jl-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-b6946c1828.54x8.p3.openshiftapps.com/rhtap/rhtap-qe:aa9a3deeda72044d3665d5a69dc94415c7e8e62c@sha256:19af93ec274cabf7d86a34f33b1f7442257841cdaca591e81e95119bd2a507d1
        name: container-image  
